const SUPABASE_URL="https://ppcvnanxajlueszgbdmu.supabase.co"
const SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwY3ZuYW54YWpsdWVzemdiZG11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzNTIyNTUsImV4cCI6MjA4ODkyODI1NX0.dMnBSHRvorviN6KwniXvx58MpcbEjyykNSNZEKev4Ns"

const supabaseClient = window.supabase.createClient(
  SUPABASE_URL,
  SUPABASE_KEY
)